config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'facilities#index'
  resources :facilities, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    member do
      get 'room_list/:per', to: 'facilities#room_list_page', as: 'room_list'
    end
  end
  resources :rooms, only: [:index, :new, :create, :destroy] do
    collection do
      get 'search'
      get 'room_list/:per', to: 'rooms#room_list_page', as: 'room_list'
    end
    resources :messages, only: [:index, :create]
  end

  get "room_list/:per" => "rooms#room_list_page"
  get "room_list" => "room#room_list"
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# CSS・・・assets/stylesheets/shared/footer.css %>
<footer>
  <p>asobiba © 2023 koon23 All rights reserved

  asobibaは、知らない人同士をつなげる無料のアプリです。施設を利用したいが一緒に利用する人がいないというニーズに応えるために開発されました。このアプリは、個人で制作され、日本国内で提供されています。
  本アプリに関する一切の著作権、商標権、知的財産権は、開発者であるkoon23に帰属します。アプリ内の情報やデザイン、機能に関する無断複製、転載、改変、配布、販売、公衆送信などの行為は、著作権法およびその他の関連法令により禁止されています。
  asobibaアプリの利用に関しては、利用規約およびプライバシーポリシーに従ってください。利用者は、アプリの利用により発生したいかなる損害についても、開発者は一切の責任を負わないことに同意したものとみなされます。</p>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header_first.css %>
<header>
<div class='top-page-header'>
  <div class='asobiba'>
    <%= link_to 'asobiba', "/" , class: "asobiba-link" %>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
        <li><%= link_to 'asobiba一覧', rooms_path, class: "room-view" %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'New施設', new_facility_path, class: "new-facility" %></li>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</div>
</header>

app/views/shared/_header_second.html.erb
<%# CSS・・・assets/stylesheets/shared/header_second.css %>
<header class='second-page-header'>
  <div class='asobiba'>
    <%= link_to 'asobiba', "/" , class: "asobiba-link" %>
  </div>
</header>