config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'facilities#index'
  resources :facilities, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    member do
      get 'room_list/:per', to: 'facilities#room_list_page', as: 'room_list'
    end
  end
  resources :rooms, only: [:index, :new, :create, :destroy] do
    collection do
      get 'search'
      get 'room_list/:per', to: 'rooms#room_list_page', as: 'room_list'
    end
    resources :messages, only: [:index, :create]
  end

  get "room_list/:per" => "rooms#room_list_page"
  get "room_list" => "room#room_list"
end

app/models/facility.rb
class Facility < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_one_attached :image
  validates :image, presence: true
  belongs_to :prefecture
  has_many :rooms, dependent: :destroy

  validates :name, presence: true
  validates :explanation, presence: true
  validates :prefecture_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }

  def self.ransackable_associations(auth_object = nil)
    %w(prefecture)
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update]
  before_action :set_facility, only: [:show, :edit, :update, :destroy, :room_list_page]
  before_action :move_to_index, only: [:edit, :destroy]
  before_action :set_page, only: [:show, :room_list_page]
  require 'httpclient'

  def index
    @facilities = Facility.all
  end

  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.new(facility_params)
    if @facility.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @rooms = @facility.rooms.paginate(page: params[:page], per_page: @page)
    set_weather
  end

  def room_list_page
    @page = params[:per]
    session[:per_page] = @page
    @rooms = @facility.rooms.paginate(page: params[:page], per_page: @page)
    set_weather
    render("show")
  end
  
  def destroy
    if @facility.destroy
      flash[:notice] = "Facility was successfully deleted."
      redirect_to "#"
    else
      flash[:alert] = "Failed to delete the facility."
      render :show
    end
  end

  def edit
  end

  def update
    if @facility.update(facility_params)
      redirect_to facility_path(@facility)
    else
      render :edit
    end
  end

  private
  def facility_params
    params.require(:facility).permit(:name, :image, :explanation, :prefecture_id, :city, :facility_link, :place_link)
                                    .merge(user_id: current_user.id)
  end

  def set_facility
    @facility = Facility.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if current_user.id != @facility.user_id
  end

  def set_weather
    if @facility.prefecture.weather_id != "000000"
      client    = HTTPClient.new
      url       = "https://weather.tsukumijima.net/api/forecast/city/#{@facility.prefecture.weather_id}"
      response  = client.get(url)
      res_json  = JSON.parse(response.body)
      print res_json
      weather = res_json["forecasts"]
      @todayWeather = weather[0]
      @tomorrowWeather = weather[1]
      @dayAfterTomorrowWeather = weather[2]
    end
  end

  def set_page
    @page = session[:per_page] || 5
  end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/edit.html.erb
<%= render "shared/header_second" %>

<div class="new-facility-body">
  <div class="facilities-register-main">
    <h2 class="facilities-register-title">登録する施設の情報を入力</h2>
    <%= form_with(model: @facility, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 施設画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        施設画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"facility-image" %>
      </div>
    </div>
    <%# /施設画像 %>
    <%# 施設名と施設説明 %>
    <div class="new-facilities">
      <div class="weight-bold-text">
        施設名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"facilities-text", id:"facilities-name", placeholder:"施設名（必須 15文字まで)", rows:"1", maxlength:"15" %>
      <div class="facilities-explain">
        <div class="weight-bold-text">
          施設の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"facilities-text", id:"facilities-info", placeholder:"施設の説明（必須 300文字まで）" ,rows:"10" ,maxlength:"300" %>
      </div>
    </div>
    <%# /施設名と施設説明 %>

    <%# 施設の場所 %>
    <div class="facilities-place">
      <div class="weight-bold-text">施設の場所</div>
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          市区町村
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :city, class:"city-text", id:"facilities-name", placeholder:"市区町村", rows:"1", maxlength:"7" %>
      </div>
    </div>
    <%# /施設の場所 %>

    <%# 施設のリンクと場所のリンク %>
    <div class="new-facilities">
      <div class="weight-bold-text">
        施設のリンク
      </div>
      <%= f.text_area :facility_link, class:"facilities-text", id:"facilities-info", placeholder:"施設のリンク（HP等）",rows:"3",  maxlength:"300" %>
      <div class="weight-bold-text">
        場所のリンク
      </div>
      <%= f.text_area :place_link, class:"facilities-text", id:"facilities-info", placeholder:"場所のリンク（マップ等）" ,rows:"3" ,maxlength:"300" %>
    </div>
    <%# /施設のリンクと場所のリンク %>

    <%# 下部ボタン %>
    <div class="register-btn-contents">
      <%= f.submit "登録する" ,class:"register-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/facilities/index.html.erb
<%= render "shared/header" %>
<body>
<div class="main">
  <%= image_tag "cachcopy.png", class:"cachcopy" %>
  <div class="asobiba-explain">
    <div class="explain-theme">
      asobibaって？
    </div>
    <div class="explain-sentence">
      今日は何して遊ぼうかな？

      そんな時は、このアプリを使って新しい出会いを楽しんでみませんか？
      あなたがオススメしたい施設ってありませんか？このアプリでは、自分で施設を登録することができます！
      好きなスポットを登録して、同じ趣味を持つ人とつながったり、新しい友達を作ったりしましょう。
      スポーツ施設で熱い試合を楽しんだり、アミューズメント施設でドキドキわくわくしたり、カフェやレストランでおしゃべりしながら美味しいものを食べたり…。自分が興味のあることを見つけて、新しい出会いをたくさん楽しもう！
      さらに、自分のお気に入りの施設を登録して、たくさんの人と交流することもできます。
      このアプリで、普段の生活にちょっぴりスパイスを加えて、楽しい思い出をたくさん作りましょう！
    </div>
  </div>
  <div class="download">
    <%= image_tag "download_foto.png", class:"download-foto" %>
    <%= link_to "/", class: "your-class" do %>
      <%= image_tag("app-store.png", alt: "App Store", class: "app-store") %>
    <% end %>
    <%= link_to "/", class: "your-class" do %>
      <%= image_tag("google-play.png", alt: "Google Play", class: "google-play") %>
    <% end %>
  </div>
  <div class="steps">
    <h2>かんたん３ステップ</h2>
    <div class="step">
      <%=image_tag "1ststep.png" %>
      <h3><span class="highlight">施設</span>を登録する</h3>
      <p>好きな施設、お気に入りの施設、使いたい施設を登録しよう！
        他のユーザーにあなたの登録した場所が広がるチャンスも！</p>
    </div>
    <div class="step">
      <%=image_tag "2ndstep.png" %>
      <h3><span class="highlight">asobiba</span>を作る</h3>
      <p>気になる施設や遊びを選んで、asobibaを作ろう！
      同じ趣味を持つ人たちと出会い、新しい発見があるかも！</p>
    </div>
    <div class="step">
      <%=image_tag "3rdstep.png" %>
      <h3>asobibaで<span class="highlight">繋がる</span></h3>
      <p>asobibaで出会った人たちと一緒に施設で遊ぼう！ 
        新しい友達や思い出をつくろう！
        　</p>
    </div>
  </div>
  <div class="facility-theme">施設一覧</div>

  <div class="facilities">
    <% @facilities.each do |facility| %>
      <%= link_to facility_path(facility.id), class: "facility-link" do %>
        <div class="facility">
          <%= image_tag facility.image, alt: "施設の写真2", class: "facility-image" %>
          <div class="facility-info">
            <p class="facility-name"><%= facility.name %></p>
            <p class="facility-location"><%= facility.prefecture.name %><%= facility.city %></p>
            <p class="facility-room-count"><%= facility.rooms.count %>asobiba</p>
          </div>
        </div>
      <% end %>
    <% end %> 
  </div>
</div>
</body>
<%= render "shared/footer" %>

app/views/facilities/new.html.erb
<%= render "shared/header_second" %>

<div class="new-facility-body">
  <div class="facilities-register-main">
    <h2 class="facilities-register-title">登録する施設の情報を入力</h2>
    <%= form_with(model: @facility, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 施設画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        施設画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"facility-image" %>
      </div>
    </div>
    <%# /施設画像 %>
    <%# 施設名と施設説明 %>
    <div class="new-facilities">
      <div class="weight-bold-text">
        施設名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"facilities-text", id:"facilities-name", placeholder:"施設名（必須 15文字まで)", rows:"1", maxlength:"15" %>
      <div class="facilities-explain">
        <div class="weight-bold-text">
          施設の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"facilities-text", id:"facilities-info", placeholder:"施設の説明（必須 300文字まで）" ,rows:"10" ,maxlength:"300" %>
      </div>
    </div>
    <%# /施設名と施設説明 %>

    <%# 施設の場所 %>
    <div class="facilities-place">
      <div class="weight-bold-text">施設の場所</div>
      <div class="form">
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          市区町村
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_area :city, class:"city-text", id:"facilities-name", placeholder:"市区町村", rows:"1", maxlength:"7" %>
      </div>
    </div>
    <%# /施設の場所 %>

    <%# 施設のリンクと場所のリンク %>
    <div class="new-facilities">
      <div class="weight-bold-text">
        施設のリンク
      </div>
      <%= f.text_area :facility_link, class:"facilities-text", id:"facilities-info", placeholder:"施設のリンク（HP等）",rows:"3",  maxlength:"300" %>
      <div class="weight-bold-text">
        場所のリンク
      </div>
      <%= f.text_area :place_link, class:"facilities-text", id:"facilities-info", placeholder:"場所のリンク（マップ等）" ,rows:"3" ,maxlength:"300" %>
    </div>
    <%# /施設のリンクと場所のリンク %>

    <%# 下部ボタン %>
    <div class="register-btn-contents">
      <%= f.submit "登録する" ,class:"register-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/facilities/show.html.erb
<%= render "shared/header" %>
<div class="fash-main">
  <div class = "fash-name">
    <%= @facility.name%>
  </div>
  <div class="fash-info">
    <div class="fash-image">
      <%= image_tag @facility.image, class: "fash-image-tag"%>
    </div>
    <div class="fash-info-right">
      <div class="fash-info-place">
        <div class="fash-category">
          場所
        </div>
        <div class="fash-content">
          <%= @facility.prefecture.name %><%= @facility.city %>
        </div>
      </div>
      <div class="fash-info-explanation">
        <div class="fash-category">
          説明
        </div>
        <div class="fash-content">
          <%= @facility.explanation %>
        </div>
      </div>
    </div>
  </div>
  <% if @facility.prefecture.weather_id != "000000"%>
    <div class="fash-weather">
      <div class="fash-weather-title">
        施設の天気
      </div>
      <div class="fash-weather-day">
        <%= @todayWeather["dateLabel"]%>
        <img src="<%= @todayWeather["image"]["url"] %>">
        <%= @todayWeather["image"]["title"]%>
      </div>
      <div class="fash-weather-tomorrow">
        <%= @tomorrowWeather["dateLabel"]%>
        <img src="<%= @tomorrowWeather["image"]["url"] %>">
        <%= @tomorrowWeather["image"]["title"]%>
      </div>
      <div class="fash-weather-day">
        <%= @dayAfterTomorrowWeather["dateLabel"]%>
        <img src="<%= @dayAfterTomorrowWeather["image"]["url"] %>">
        <%= @dayAfterTomorrowWeather["image"]["title"]%>
      </div>
    </div>
  <% end %>
  <div class="fash-links">
    <div class="fash-link">
      <div class="fash-category">
        施設のリンク
      </div>
      <div class="fash-content">
        <%= link_to @facility.facility_link, @facility.facility_link, target: '_blank' %>
      </div>
    </div>
    <div class="fash-link">
      <div class="fash-category">
        場所のリンク
      </div>
      <div class="fash-content">
        <%= link_to @facility.place_link, @facility.place_link, target: '_blank' %>
      </div>
    </div>
  </div>
  <% if user_signed_in? && current_user.id == @facility.user_id %>
    <div class="fash-btn-contents">
      <div class="fash-blue-box">
        <%= link_to "施設を編集する", edit_facility_path(@facility.id), method: :get, class: "fash-btn" %>
      </div>
      <div class="fash-red-box">
        <%= link_to "施設を削除する", facility_path(@facility), method: :delete, data: { confirm: '本当に削除しますか？' }, class:"fash-btn" %>
      </div>
    </div>
  <% end %>
  <div class="fash-aso-commands">
    <div class="fash-index">
      asobiba一覧
    </div>
    <div class="fash-green-box">
      <%= link_to "asobibaを作成する", new_room_path(facility_id: @facility.id), class: "fash-btn" %>
    </div>
  </div>
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <%= @page %>
      <label>件表示中</label>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li><%= link_to("3", room_list_facility_path(@facility, per: 3)) %></li>
      <li><%= link_to("5", room_list_facility_path(@facility, per: 5)) %></li>
      <li><%= link_to("10", room_list_facility_path(@facility, per: 10)) %></li>
      <li><%= link_to("20", room_list_facility_path(@facility, per: 20)) %></li>
    </ul>
  </div>
  <div class = "fash-rooms">
    <% @rooms.each do |room| %>
      <div class="fash-asobiba">
          <p class="fash-asobiba-title"><%= room.title%></p>
        <div class="fash-asobiba-left">
          <p class="fash-asobiba-event"><%= room.event.name %></p>
          <p class="fash-asobiba-count"><%= room.messages.count %>chat</p>
        </div>
        <div class="fash-join">
          <%= link_to "参加<br>する".html_safe, room_messages_path(room), class:"fash-join-btn" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class = "roin-page">
    <%= will_paginate @rooms, renderer: WillPaginate::ActionView::LinkRenderer, previous_label: '&lt; 前へ', next_label: '次へ &gt;' %>
  </div>
</div>
<%= render "shared/footer" %>