config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'facilities#index'
  resources :facilities, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    member do
      get 'room_list/:per', to: 'facilities#room_list_page', as: 'room_list'
    end
  end
  resources :rooms, only: [:index, :new, :create, :destroy] do
    collection do
      get 'search'
      get 'room_list/:per', to: 'rooms#room_list_page', as: 'room_list'
    end
    resources :messages, only: [:index, :create]
  end

  get "room_list/:per" => "rooms#room_list_page"
  get "room_list" => "room#room_list"
end

app/models/room.rb
class Room < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :event
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  belongs_to :facility
  has_many :messages, dependent: :destroy

  validates :title, presence: true
  validates :event_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }

  def self.ransackable_associations(auth_object = nil)
    %w(facility)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :set_facility, only: [:new, :create]
  before_action :set_page, only: [:index, :room_list_page]

  def index
    @facility = Facility.find_by(id: params[:facility_id])
    @facilities = Facility.all
    @rooms = Room.paginate(page: params[:page], per_page: @page)
  end

  def room_list_page
    @page = params[:per]
    session[:per_page] = @page
    @rooms = Room.paginate(page: params[:page], per_page: @page)
    render("index")
  end

  def new
    @room = Room.new
  end

  def create
    @room = @facility.rooms.build(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  def search
    @facilities = Facility.all
    @q = Room.includes(:facility).ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  private
  def room_params
    params.require(:room).permit(:title, :event_id, :facility_id, user_ids: [])
  end
  def set_facility
    @facility = Facility.find(params[:facility_id] || params[:room][:facility_id])
  end
  def set_page
    @page = session[:per_page] || 5
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<%= render "shared/header" %>
<div class="roin-main">
  <div class="roin-top">
    <div class="roin-title">
      asobiba一覧
    </div>
    <div class="roin-serch">
      <%= link_to "asobiba検索", search_rooms_path, class: "roin-serch-text" %>
    </div>
  </div>
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <%= @page %>
      <label>件表示中</label>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li><%= link_to("3", room_list_rooms_path(per: 3)) %></li>
      <li><%= link_to("5", room_list_rooms_path(per: 5)) %></li>
      <li><%= link_to("10", room_list_rooms_path(per: 10)) %></li>
      <li><%= link_to("20", room_list_rooms_path(per: 20)) %></li>
    </ul>
  </div>
  <div class = "roin-rooms">
    <% @rooms.each do |room| %>
      <div class="roin-room">
        <div class="roin-room-header"><%= room.title%></div>
        <div class="roin-room-left">
          <div class="roin-facility">施設名</div>
          <div class="roin-event">種目名</div>
          <div class="roin-count">chat数</div>
        </div>
        <div class="roin-room-right">
          <div class="roin-facility"><%= room.facility.name%></div>
          <div class="roin-event"><%= room.event.name %></div>
          <div class="roin-count"><%= room.messages.count %>chat</div>
        </div>
        <% button_class = case room.id % 4
          when 0
            "bg-green"
          when 1
            "bg-red"
          when 2
            "bg-blue"
          when 3
            "bg-yellow"
          end
        %>
        <div class="roin-join">
          <%= link_to "参加<br>する".html_safe, room_messages_path(room), class: "roin-join-btn #{button_class}" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class = "roin-page">
  <%= will_paginate @rooms, renderer: WillPaginate::ActionView::LinkRenderer, previous_label: '&lt; 前へ', next_label: '次へ &gt;' %>
</div>
<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<%= render "shared/header_second" %>
<div class="rone-back">
<%= form_with model: @room, url: rooms_path, class: 'rone-main', local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <%= f.hidden_field :facility_id, value: @facility.id %>
    <div class="rone-title">
      登録するasobibaの情報を入力
    </div>
    <div class="rone-in">
      <div class="rone-info">
        <div class="rone-category">
          施設名
        </div>
        <div class="rone-facility">
          <%= @facility.name%>
        </div>
      </div>
      <div class="rone-info">
        <div class="rone-category">
          施設の場所
        </div>
        <div class="rone-facility">
          <%= @facility.prefecture.name%><%= @facility.city%>
        </div>
      </div>
      <div class="rone-info">
        <div class="rone-category">
          asobiba名
          <span class="indispensable">必須</span>
        </div>
        <div class="rone-facility">
          <%= f.text_area :title, class:"rone-text", id:"facilities-name", placeholder:"asobiba名（必須 20文字まで)", rows:"1", maxlength:"20" %>
        </div>
      </div><div class="rone-info">
        <div class="rone-category">
          種目の選択
          <span class="indispensable">必須</span>
        </div>
        <div class="rone-facility">
          <%= f.collection_select(:event_id, Event.all, :id, :name, {}, {class:"rone-select-box", id:"item-shipping-fee-status"}) %>
        </div>
      </div>
      <%# 下部ボタン %>
      <div class="register-btn-contents">
        <%= f.submit "登録する" ,class:"register-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/rooms/search.html.erb
<%= render "shared/header" %>
<div class="roin-main">
  <div class="roin-top">
    <div class="roin-title">
      asobiba一覧
    </div>
  </div>
  <%= search_form_for @q, url: search_rooms_path, html: {id: "detailed-search-form"} do |f| %>
    <div class="rose-search">
      <div class="search-field">
        <%= f.label :title_cont, 'asobiba名' %>
        <br>
        <%= f.search_field :title_cont, placeholder: 'asobiba名' %>
      </div>
      <div class="search-field">
        <%= f.label :facility_prefecture_id_eq, '都道府県' %>
        <br>
        <%= f.collection_select(:facility_prefecture_id_eq, Prefecture.options, :id, :name, {include_blank: "---", class:"rone-select-box", id:"item-shipping-fee-status"}) %>
      </div>
      <div class="search-field">
        <%= f.label :event_id_eq, '種目名' %>
        <br>
        <%= f.collection_select(:event_id_eq, Event.options, :id, :name, {include_blank: "---", class:"rone-select-box", id:"item-shipping-fee-status"}) %>
      </div>
      <%= f.submit '検索', class: 'rose-btn' %>
    </div>
  <% end %>
  <div class = "roin-rooms">
    <% @rooms.each do |room| %>
      <div class="roin-room">
        <div class="roin-room-header"><%= room.title%></div>
        <div class="roin-room-left">
          <div class="roin-facility">施設名</div>
          <div class="roin-event">種目名</div>
          <div class="roin-count">chat数</div>
        </div>
        <div class="roin-room-right">
          <div class="roin-facility"><%= room.facility.name%></div>
          <div class="roin-event"><%= room.event.name %></div>
          <div class="roin-count"><%= room.messages.count %>chat</div>
        </div>
        <% button_class = case room.id % 4
          when 0
            "bg-green"
          when 1
            "bg-red"
          when 2
            "bg-blue"
          when 3
            "bg-yellow"
          end
        %>
        <div class="roin-join">
          <%= link_to "参加<br>する".html_safe, room_messages_path(room), class: "roin-join-btn #{button_class}" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>